[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$5xyDsLZ2LiXkXMvZe0.J8Q$/5pMSDZDk4KDEbjwCxQPh0rlGSHdKKs/By4N469O6xcyv0tTsRLJtKxkvltYplxaUCMUslxt9meaN8qA6BLkTA
xmlrpc_port = 8069

